version: '3.8'

services:
  timed:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - RUST_LOG=info
    restart: unless-stopped

  time-testnet:
    build: .
    ports:
      - "9080:8080"
      - "9081:8081"
    volumes:
      - ./config/testnet.toml:/app/config/mainnet.toml
      - ./data-testnet:/app/data
    environment:
      - RUST_LOG=debug
    restart: unless-stopped
